spring.application.name=BatchSystem

# =========================
# Database
# =========================
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3308/managing
#spring.datasource.username=system
#spring.datasource.password=0806
spring.datasource.url=jdbc:mariadb://localhost:3306/managingTest
spring.datasource.username=root
spring.datasource.password=0806

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.stock.batch.domain

# =========================
# HikariCP
# =========================
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20

# =========================
# Batch file path
# =========================
batch.path.root=D:/STOCK_PROJECT_V2/LOCAL_FILE
batch.path.in=${batch.path.root}/BATCH_IN
batch.path.out=${batch.path.root}/BATCH_OUT
batch.path.archive=${batch.path.root}/ARCHIVE
batch.path.error=${batch.path.root}/ERROR

# =========================
# Python Execution (LOCAL)
# =========================
# ? conda ? ?? python ?? ??
python.exec.cmd=C:/Users/ysh01/anaconda3/envs/stock_batch_py39/python.exe
python.workdir=D:/STOCK_PROJECT_V2/STOCK-DATA-PIPELINE
python.path=D:/STOCK_PROJECT_V2/STOCK-DATA-PIPELINE
python.encoding=utf-8

app.env=local