spring.application.name=BatchSystem

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://infra-mariadb:3306/managing
spring.datasource.username=system
spring.datasource.password=0806

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.stock.batch.domain

batch.path.root=/data
batch.path.in=${batch.path.root}/BATCH_IN
batch.path.out=${batch.path.root}/BATCH_OUT
batch.path.archive=${batch.path.root}/ARCHIVE
batch.path.error=${batch.path.root}/ERROR

python.exec.cmd=python
python.workdir=/workspace
python.path=/workspace
python.encoding=utf-8

app.env=docker
